---
- name: Verificar caducidad de contraseñas y enviar alerta por Telegram
  hosts: all
  become: yes
  vars:
    # Configuración de Telegram
    telegram_bot_token: "7752861813:AAFmFHaKUIPgo9Qsr5sS2DDV_vSbCv9t4wY"
    telegram_chat_id: "@andyjvf_bot"
    dias_alerta: 30                      # Alertar cuando falten 30 días para expirar
    
    # Configuración de políticas de contraseñas
    max_dias_clave: 90                   # Máximo de días para cambiar la contraseña
    min_dias_clave: 1                    # Mínimo de días para cambiar la contraseña
    dias_aviso_clave: 30                 # Días de aviso antes de expirar

  tasks:
    - name: Obtener información de expiración de contraseñas
      shell: |
        cat /etc/shadow | awk -F: '{
          if ($2 != "*" && $2 != "!!") {
            cmd = "date -d \""$3" days\" +%s";
            cmd | getline last_change;
            close(cmd);
            cmd = "date +%s";
            cmd | getline now;
            close(cmd);
            max_days = $5;
            if (max_days == "") max_days = {{ max_dias_clave }};
            expire = last_change + (max_days * 86400);
            remaining = (expire - now)/86400;
            if (remaining < {{ dias_alerta }} && remaining > 0) {
              print $1":"int(remaining)" días";
            }
          }
        }'
      register: usuarios_por_expiar
      changed_when: false

    - name: Enviar alerta por Telegram si hay usuarios con contraseña por expirar
      uri:
        url: "https://api.telegram.org/bot{{ telegram_bot_token }}/sendMessage"
        method: POST
        body_format: json
        body:
          chat_id: "{{ telegram_chat_id }}"
          text: |
            🔔 **Alerta de Caducidad de Contraseñas** 🔔
            🖥️ Host: {{ inventory_hostname }}
            📅 Política: Cambio cada {{ max_dias_clave }} días (Aviso a {{ dias_aviso_clave }} días)
            
            👤 Usuarios con contraseña por expirar:
            {% if usuarios_por_expiar.stdout_lines %}
            {% for usuario in usuarios_por_expiar.stdout_lines %}
            - {{ usuario }}
            {% endfor %}
            {% else %}
            ✅ No hay usuarios con contraseña por expirar.
            {% endif %}
            
            ⏳ Próximo chequeo: {{ ansible_date_time.date }}
          parse_mode: "markdown"
      when: usuarios_por_expiar.stdout_lines | length > 0
      delegate_to: localhost
      run_once: true

    - name: Enviar confirmación cuando no hay usuarios por expirar
      uri:
        url: "https://api.telegram.org/bot{{ telegram_bot_token }}/sendMessage"
        method: POST
        body_format: json
        body:
          chat_id: "{{ telegram_chat_id }}"
          text: |
            🔍 **Verificación de Contraseñas Completa**
            🖥️ Host: {{ inventory_hostname }}
            ✅ Resultado: No hay usuarios con contraseña por expirar en los próximos {{ dias_alerta }} días
            📅 Próximo chequeo: {{ ansible_date_time.date }}
          parse_mode: "markdown"
      when: usuarios_por_expiar.stdout_lines | length == 0
      delegate_to: localhost
      run_once: true
