---
- name: Verificación de caducidad de contraseñas para grupo manager en AlmaLinux
  hosts: all
  remote_user: kopet
  gather_facts: true

  vars:
    telegram_bot_token: "7752861813:AAFmFHaKUIPgo9Qsr5sS2DDV_vSbCv9t4wY"
    telegram_chat_id: "@andyjvf_bot"
    dias_alerta: 30
    grupo_objetivo: "manager"  # Especificamos el grupo a verificar

  tasks:
    - name: Verificar si el grupo manager existe
      shell: "getent group {{ grupo_objetivo }}"
      register: grupo_check
      changed_when: false
      ignore_errors: yes

    - name: Obtener usuarios del grupo manager con contraseñas por expirar
      block:
        - name: Obtener lista de usuarios del grupo manager
          shell: "getent group {{ grupo_objetivo }} | cut -d: -f4 | tr ',' '\n'"
          register: usuarios_manager
          changed_when: false

        - name: Verificar expiración de contraseñas para cada usuario
          shell: |
            today=$(date +%s)
            user="{{ item }}"
            expiry_info=$(sudo chage -l "$user" 2>/dev/null | grep "Password expires")
            if [[ "$expiry_info" == *"never"* ]]; then
              echo ""
            elif [[ "$expiry_info" =~ ([A-Za-z]{3} [0-9]{2}, [0-9]{4}) ]]; then
              expiry_date=$(date -d "${BASH_REMATCH[1]}" +%s)
              remaining_days=$(( (expiry_date - today) / 86400 ))
              if [ $remaining_days -gt 0 ] && [ $remaining_days -lt {{ dias_alerta }} ]; then
                echo "$user:$remaining_days días"
              fi
            fi
          args:
            executable: /bin/bash
          with_items: "{{ usuarios_manager.stdout_lines[0].split(',') }}"
          register: usuarios_por_expiar
          changed_when: false
      when: grupo_check is not failed

    - name: Enviar reporte a Telegram
      uri:
        url: "https://api.telegram.org/bot{{ telegram_bot_token }}/sendMessage"
        method: POST
        body_format: json
        body:
          chat_id: "{{ telegram_chat_id }}"
          text: |
            🔐 *Reporte de Contraseñas - {{ ansible_hostname }}*
            *Grupo verificado*: {{ grupo_objetivo }}
            *Sistema*: {{ ansible_distribution }} {{ ansible_distribution_version }}
            
            {% if grupo_check is failed %}
            ❌ El grupo {{ grupo_objetivo }} no existe en el sistema
            {% elif usuarios_por_expiar.results | map(attribute='stdout') | select('match','.+') | list %}
            *Usuarios por expirar (menos de {{ dias_alerta }} días)*:
            {% for result in usuarios_por_expiar.results %}
              {% if result.stdout %}
              - {{ result.stdout }}
              {% endif %}
            {% endfor %}
            {% else %}
            ✅ No hay usuarios del grupo {{ grupo_objetivo }} con contraseña por expirar
            {% endif %}
            
            *Detalles*:
            - Usuario ejecutor: kopet
            - Fecha de verificación: {{ ansible_date_time.date }}
          parse_mode: "markdown"
      delegate_to: localhost
      run_once: true
