---
- name: Verificación de caducidad de contraseñas con alerta en Telegram
  hosts: all
  become: true
  become_method: sudo
  become_user: root
  gather_facts: true

  vars:
    telegram_bot_token: "7752861813:AAFmFHaKUIPgo9Qsr5sS2DDV_vSbCv9t4wY"
    telegram_chat_id: "@andyjvf_bot"
    dias_alerta: 30
    max_dias_clave: 90

  tasks:
    - name: Verificar que la escalación de privilegios funciona
      command: whoami
      register: whoami_result
      changed_when: false

    - name: Mostrar usuario actual (para depuración)
      debug:
        var: whoami_result.stdout

    - name: Obtener usuarios con contraseña por expirar (método compatible)
      shell: |
        today=$(date +%s)
        while IFS=: read -r user _ last_change _ max_days _; do
          if [[ -n "$last_change" && "$max_days" =~ ^[0-9]+$ ]]; then
            expire_date=$((last_change * 86400 + max_days * 86400))
            remaining_days=$(( (expire_date - today) / 86400 ))
            if (( remaining_days > 0 && remaining_days < {{ dias_alerta }} )); then
              echo "$user:$remaining_days días"
            fi
          fi
        done < <(awk -F: '$2 !~ /^[*!]/ {print $1":"$3":"$5}' /etc/shadow)
      args:
        executable: /bin/bash
      register: usuarios_por_expiar
      changed_when: false

    - name: Enviar alerta consolidada por Telegram
      uri:
        url: "https://api.telegram.org/bot{{ telegram_bot_token }}/sendMessage"
        method: POST
        body_format: json
        body:
          chat_id: "{{ telegram_chat_id }}"
          text: |
            🔐 *Reporte de Caducidad de Contraseñas*
            *Host*: {{ inventory_hostname }}
            *Usuario ejecutor*: {{ whoami_result.stdout }}
            
            {% if usuarios_por_expiar.stdout_lines %}
            *Usuarios por expirar (menos de {{ dias_alerta }} días)*:
            {% for usuario in usuarios_por_expiar.stdout_lines %}
            - {{ usuario }}
            {% endfor %}
            {% else %}
            *✅ Todos los usuarios cumplen con la política*
            {% endif %}
            
            *Política actual*: 
            - Cambio cada {{ max_dias_clave }} días
            - Aviso con {{ dias_alerta }} días de anticipación
          parse_mode: "markdown"
      delegate_to: localhost
      run_once: true
