---
- name: Verificación de caducidad de contraseñas para usuario kopet
  hosts: all
  remote_user: kopet
  gather_facts: false

  vars:
    telegram_bot_token: "7752861813:AAFmFHaKUIPgo9Qsr5sS2DDV_vSbCv9t4wY"
    telegram_chat_id: "@andyjvf_bot"
    dias_alerta: 30
    max_dias_clave: 90

  tasks:
    - name: Verificar permisos del usuario kopet en /etc/shadow
      stat:
        path: /etc/shadow
      register: shadow_perms

    - name: Verificar si kopet puede leer /etc/shadow
      assert:
        that:
          - shadow_perms.stat.exists
          - shadow_perms.stat.readable
        fail_msg: "El usuario kopet no tiene permisos para leer /etc/shadow"
        success_msg: "Permisos de lectura confirmados"

    - name: Obtener usuarios con contraseña por expirar (método seguro)
      shell: |
        # Método que usa getent en lugar de acceso directo a /etc/shadow
        today=$(date +%s)
        getent shadow | awk -F: '$2 !~ /^[*!]/ {print $1":"$3":"$5}' | while IFS=: read -r user last_change max_days; do
          if [ -n "$last_change" ] && [ "$max_days" -eq "$max_days" ] 2>/dev/null; then
            expire_date=$((last_change * 86400 + max_days * 86400))
            remaining_days=$(( (expire_date - today) / 86400 ))
            if [ $remaining_days -gt 0 ] && [ $remaining_days -lt {{ dias_alerta }} ]; then
              echo "$user:$remaining_days días"
            fi
          fi
        done
      register: usuarios_por_expiar
      changed_when: false

    - name: Enviar reporte a Telegram
      uri:
        url: "https://api.telegram.org/bot{{ telegram_bot_token }}/sendMessage"
        method: POST
        body_format: json
        body:
          chat_id: "{{ telegram_chat_id }}"
          text: |
            🔐 *Reporte de Contraseñas - {{ inventory_hostname }}*
            
            *Ejecutado como*: kopet
            *Método usado*: getent shadow
            
            {% if usuarios_por_expiar.stdout_lines %}
            *⚠️ Usuarios por expirar (menos de {{ dias_alerta }} días)*:
            {% for linea in usuarios_por_expiar.stdout_lines %}
            - {{ linea }}
            {% endfor %}
            {% else %}
            *✅ Todas las contraseñas están vigentes*
            {% endif %}
            
            *Política*:
            - Cambio cada {{ max_dias_clave }} días
            - Aviso con {{ dias_alerta }} días de anticipación
          parse_mode: "markdown"
      delegate_to: localhost
      run_once: true
