---
- name: Verificar caducidad de contraseñas y enviar alerta por Telegram
  hosts: all
  become: yes
  vars:
    ansible_become_flags: ''
    telegram_bot_token: "7752861813:AAFmFHaKUIPgo9Qsr5sS2DDV_vSbCv9t4wY"
    telegram_chat_id: "@andyjvf_bot"
    dias_alerta: 30
    
  tasks:
    - name: Verificar usuarios con contraseña por expirar (método compatible)
      shell: |
        today=$(date +%s)
        while IFS=: read -r user _ last_change _ max_days _; do
          if [[ -n "$last_change" && "$max_days" =~ ^[0-9]+$ ]]; then
            expire_date=$((last_change * 86400 + max_days * 86400))
            remaining_days=$(( (expire_date - today) / 86400 ))
            if (( remaining_days > 0 && remaining_days < dias_alerta )); then
              echo "$user:$remaining_days días"
            fi
          fi
        done < <(awk -F: '$2 !~ /^[*!]/ {print $1":"$3":"$5}' /etc/shadow)
      args:
        executable: /bin/bash
      register: usuarios_por_expiar
      changed_when: false
      environment:
        dias_alerta: "{{ dias_alerta }}"

    - name: Enviar alerta por Telegram
      uri:
        url: "https://api.telegram.org/bot{{ telegram_bot_token }}/sendMessage"
        method: POST
        body_format: json
        body:
          chat_id: "{{ telegram_chat_id }}"
          text: |
            🔔 Alerta de Contraseñas
            Host: {{ inventory_hostname }}
            
            {% if usuarios_por_expiar.stdout_lines %}
            Usuarios por expirar:
            {% for linea in usuarios_por_expiar.stdout_lines %}
            - {{ linea }}
            {% endfor %}
            {% else %}
            ✅ Todas las contraseñas están al día
            {% endif %}
          parse_mode: "markdown"
      delegate_to: localhost
      run_once: true
