---
- name: Crear VMs Proxmox usando comandos shell
  hosts: localhost
  gather_facts: false
  vars:
    template_id: 101
    storage: "pesudfsis155"
    base_name: "PRXMOVARG"
    vm_ids: "{{ range(301, 302) | list }}"

  tasks:
    - name: Crear VM {{ item }} usando comando qm
      ansible.builtin.shell: |
        qm clone {{ template_id }} {{ item }} \
          --name {{ base_name }}{{ item }} \
          --storage {{ storage }} \
          --full true
      args:
        executable: /bin/bash
      loop: "{{ vm_ids }}"
      register: clone_result
      async: 1800
      poll: 10

    - name: Mostrar resultado
      debug:
        var: clone_result.results[ansible_loop.index0].stdout
      loop: "{{ vm_ids }}"
      loop_control:
        index_var: ansible_loop.index0
