---
- name: Crear VMs Proxmox desde Template
  hosts: all
  gather_facts: false
  vars:
    template_id: 101
    storage: "pesudfsis155"
    base_name: "PRXMOVARG"
    vm_ids: "{{ range(301, 302) | list }}"

  tasks:
    - name: Verificar que el comando qm existe
      command: which qm
      register: qm_check
      changed_when: false

    - name: Mostrar informacion del despliegue
      debug:
        msg: |
          INICIANDO CREACION DE VMs
          ==========================
          Servidor Proxmox: {{ inventory_hostname }}
          Comando qm: {{ qm_check.stdout }}
          Total VMs: {{ vm_ids | length }}
          Template ID: {{ template_id }}
          Storage: {{ storage }}
          Base Name: {{ base_name }}

    - name: Crear VMs usando comando qm
      shell: |
        qm clone {{ template_id }} {{ item }} \
          --name {{ base_name }}{{ item }} \
          --storage {{ storage }} \
          --full true
      args:
        executable: /bin/bash
      loop: "{{ vm_ids }}"
      async: 1800
      poll: 10
      register: vm_creation

    - name: Mostrar resumen final
      debug:
        msg: |
          PROCESO COMPLETADO
          ==================
          VMs procesadas: {{ vm_ids | length }}
          Resultados por VM:
          {% for result in vm_creation.results %}
          VM {{ result.item }}: {{ 'CREADA' if result.rc == 0 else 'ERROR - ' + result.stderr }}
          {% endfor %}
