---
- name: Crear VM con configuración completa
  hosts: all
  gather_facts: false
  collections:
    - community.vmware
  
  vars:
    vcenter_hostname: "{{ vcenter_host }}"
    vcenter_username: "{{ lookup('env', 'VMWARE_USER') }}"
    vcenter_password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
    datacenter_name: "{{ datacenter }}"
    template_name: "{{ template }}"
    vm_name: "{{ nueva_vm }}"
    folder: "{{ folder }}"
    
  tasks:
    - name: Crear VM con personalización (solo para usuario STSO)
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
        datacenter: "{{ datacenter_name }}"
        name: "{{ vm_name }}"
        state: poweredon
        template: "{{ template_name }}"
        folder: "{{ folder }}"
        customization_spec: "MOVPER"  # Crea usuario STSO
        networks:
          - name: "Movistar Peru 122"
            device_type: "vmxnet3"
            start_connected: true
            type: "dhcp"
        wait_for_ip_address: false
      delegate_to: localhost
      register: deploy_vm

    - name: Esperar 30 minutos para personalización completa
      pause:
        minutes: 30  # ⬅️ TIEMPO REAL según pruebas
      when: deploy_vm.changed

    - name: Forzar cambio de hostname (SIEMPRE después de 30 min)
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
        datacenter: "{{ datacenter_name }}"
        name: "{{ vm_name }}"
        customization:
          hostname: "{{ vm_name }}"
        state: poweredon
      delegate_to: localhost
      when: deploy_vm.changed

    - name: Esperar 5 minutos para reinicio del hostname
      pause:
        minutes: 5
      when: deploy_vm.changed

    - name: Verificación final
      vmware_guest_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
        datacenter: "{{ datacenter_name }}"
        name: "{{ vm_name }}"
      register: final_info
      delegate_to: localhost

    - name: Mostrar resultado final
      debug:
        msg: |
          ✅ CONFIGURACIÓN COMPLETADA
          🖥️  VM: {{ vm_name }}
          📍 IP: {{ final_info.instance.ipv4 | default('Asignación pendiente') }}
          🔧 Hostname: {{ final_info.instance.guest_name | default('Configurado - reiniciando') }}
          👤 Usuario STSO: Creado y en grupo Administradores
          ⏱️  Tiempo total: ~35 minutos
