---
- name: Crear VM con usuario STSO automático
  hosts: all
  gather_facts: false
  collections:
    - community.vmware
  
  vars:
    vcenter_hostname: "{{ vcenter_host }}"
    vcenter_username: "{{ lookup('env', 'VMWARE_USER') }}"
    vcenter_password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
    datacenter_name: "{{ datacenter }}"
    template_name: "{{ template }}"
    vm_name: "{{ nueva_vm }}"
    folder: "{{ folder }}"
    
  tasks:
    - name: Crear VM con personalización
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
        datacenter: "{{ datacenter_name }}"
        name: "{{ vm_name }}"
        state: poweredon
        template: "{{ template_name }}"
        folder: "{{ folder }}"
        customization_spec: "MOVPER"  # Para evitar OOBE y crear STSO
        networks:
          - name: "Movistar Peru 122"
            device_type: "vmxnet3"
            start_connected: true
            type: "dhcp"
        wait_for_ip_address: true
      delegate_to: localhost
      register: deploy_vm

    - name: Esperar personalización inicial
      pause:
        minutes: 30
      when: deploy_vm.changed

    - name: Forzar cambio de hostname
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
        datacenter: "{{ datacenter_name }}"
        name: "{{ vm_name }}"
        customization:
          hostname: "{{ vm_name }}"  # ⬅️ FORZAR hostname aquí
        state: poweredon
      delegate_to: localhost
      when: deploy_vm.changed

    - name: Esperar reinicio por cambio de hostname
      pause:
        minutes: 6
      when: deploy_vm.changed

    - name: Mostrar resultado final
      debug:
        msg: |
          ✅ VM {{ vm_name }} creada exitosamente
          📍 IP: {{ deploy_vm.instance.ipv4 }}
          🖥️  Hostname: {{ vm_name }} (forzado)
          👤 Usuario STSO creado automáticamente
          🔑 Password: Konecta2025$$
