---
- name: Crear VM desde template en vCenter con personalización
  hosts: all
  gather_facts: false
  collections:
    - community.vmware
  
  vars:
    vcenter_hostname: "{{ vcenter_host }}"
    vcenter_username: "{{ lookup('env', 'VMWARE_USER') }}"
    vcenter_password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
    datacenter_name: "{{ datacenter }}"
    template_name: "{{ template }}"
    vm_name: "{{ nueva_vm }}"
    folder: "{{ folder }}"
    cluster_name: "{{ cluster | default(omit) }}"
    datastore_name: "{{ datastore | default(omit) }}"
    
    # Nuevas variables para personalización
    vm_ip: "{{ ip_address }}"
    vm_netmask: "{{ netmask | default('255.255.255.0') }}"
    vm_gateway: "{{ gateway }}"
    vm_dns_servers: "{{ dns_servers | default(['172.57.152.8', '172.57.152.6']) }}"
    vm_domain: "{{ domain | default('KTINKIY.LOCAL') }}"
    win_username: "{{ win_user | default('STSO') }}"
    win_password: "{{ win_pass }}"
    
  tasks:
    - name: Crear VM desde template con personalización
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
        datacenter: "{{ datacenter_name }}"
        name: "{{ vm_name }}"
        state: poweredon
        template: "{{ template_name }}"
        folder: "{{ folder }}"
        cluster: "{{ cluster_name }}"
        datastore: "{{ datastore_name }}"
        wait_for_ip_address: true
        
        # Personalización para Windows
        customization:
          autologon: true
          autologoncount: 1
          fullname: "STSO"
          orgname: "MOVPERU"
          # Credenciales de administrador
          password: "{{ win_password }}"
          # Configuración de red
          dns_servers: "{{ vm_dns_servers }}"
          domain: "{{ vm_domain }}"
          gateway: "{{ vm_gateway.split(',') | list }}"
          ipaddress: "{{ vm_ip }}"
          netmask: "{{ vm_netmask }}"
          # Opciones de Windows
          runonce: []
          timezone: 35  # Hora de Perú (UTC-5)
          hostname: "{{ vm_name }}"
          # Especificar que es Windows
          type: "sysprep"
          sysprep:
            gui_unattended:
              auto_logon: true
              auto_logon_count: 1
              password:
                value: "{{ win_password }}"
              timezone: 35
            user_data:
              computer_name: "{{ vm_name }}"
              full_name: "STSO"
              org_name: "MOVPERU"
              product_id: ""  # Dejar vacío si usa KMS/MAK general
        networks:
          - name: "{{ network_name | default('VM Network') }}"
            ip: "{{ vm_ip }}"
            netmask: "{{ vm_netmask }}"
            gateway: "{{ vm_gateway }}"
            dns_servers: "{{ vm_dns_servers | join(',') }}"
            start_connected: true
            
      delegate_to: localhost
      register: deploy_vm

    - name: Esperar a que la VM esté completamente lista
      pause:
        minutes: 3
      when: deploy_vm.changed

    - name: Mostrar información de la VM creada
      debug:
        var: deploy_vm.instance.ipv4
