- name: Crear VM con personalización (usar spec MOVPER)
  hosts: localhost
  gather_facts: false
  collections:
    - community.vmware

  vars:
    vcenter_hostname: "{{ vcenter_host }}"
    vcenter_username: "{{ lookup('env','VMWARE_USER') }}"
    vcenter_password: "{{ lookup('env','VMWARE_PASSWORD') }}"
    datacenter_name: "{{ datacenter }}"
    template_name: "{{ template }}"
    vm_name: "{{ nueva_vm }}"
    folder: "{{ folder }}"

  tasks:
    - name: Crear VM desde plantilla usando spec MOVPER (no esperar IP)
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
        datacenter: "{{ datacenter_name }}"
        name: "{{ vm_name }}"
        state: poweredon
        template: "{{ template_name }}"
        folder: "{{ folder }}"
        customization_spec: "MOVPER"
        # quitar wait_for_ip_address si no quieres esperar la IP
        wait_for_ip_address: false
      register: deploy_vm
