---
- name: Crear VM y configurar hostname
  hosts: all
  gather_facts: false
  collections:
    - community.vmware
    - community.windows
  
  vars:
    vcenter_hostname: "{{ vcenter_host }}"
    vcenter_username: "{{ lookup('env', 'VMWARE_USER') }}"
    vcenter_password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
    datacenter_name: "{{ datacenter }}"
    template_name: "{{ template }}"
    vm_name: "{{ nueva_vm }}"
    folder: "{{ folder }}"
    
  tasks:
    - name: Crear VM con personalización básica
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
        datacenter: "{{ datacenter_name }}"
        name: "{{ vm_name }}"
        state: poweredon
        template: "{{ template_name }}"
        folder: "{{ folder }}"
        customization_spec: "MOVPER"
        networks:
          - name: "Movistar Peru 122"
            device_type: "vmxnet3"
            start_connected: true
            type: "dhcp"
        wait_for_ip_address: true
      delegate_to: localhost
      register: deploy_vm

    - name: Esperar 30 minutos para personalización
      pause:
        minutes: 30
      when: deploy_vm.changed

    - name: Cambiar hostname via PowerShell
      community.windows.win_shell: |
        # Verificar hostname actual
        $currentHostname = hostname
        Write-Output "Hostname actual: $currentHostname"
        
        if ($currentHostname -ne "{{ vm_name }}") {
            Write-Output "Cambiando hostname a: {{ vm_name }}"
            Rename-Computer -NewName "{{ vm_name }}" -Force
            Write-Output "Reiniciando en 30 segundos..."
            shutdown /r /t 30 /c "Reinicio por cambio de hostname"
        } else {
            Write-Output "Hostname ya es correcto: {{ vm_name }}"
        }
      delegate_to: "{{ deploy_vm.instance.ipv4 }}"
      when: 
        - deploy_vm.changed
        - deploy_vm.instance.ipv4 is defined

    - name: Esperar reinicio
      pause:
        minutes: 2
      when: deploy_vm.changed

    - name: Verificar hostname después del reinicio
      community.windows.win_shell: hostname
      delegate_to: "{{ deploy_vm.instance.ipv4 }}"
      register: hostname_result
      when: deploy_vm.changed

    - name: Mostrar resultado
      debug:
        msg: |
          ✅ CONFIGURACIÓN COMPLETADA
          🖥️  Hostname final: {{ hostname_result.stdout }}
          👤 Usuario STSO: Creado
          📍 IP: {{ deploy_vm.instance.ipv4 }}
