---
- name: Crear VM desde template en vCenter con personalización
  hosts: all
  gather_facts: false
  collections:
    - community.vmware
  
  vars:
    vcenter_hostname: "{{ vcenter_host }}"
    vcenter_username: "{{ lookup('env', 'VMWARE_USER') }}"
    vcenter_password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
    datacenter_name: "{{ datacenter }}"
    template_name: "{{ template }}"
    vm_name: "{{ nueva_vm }}"
    folder: "{{ folder }}"
    cluster_name: "{{ cluster | default(omit) }}"
    datastore_name: "{{ datastore | default(omit) }}"
    
  tasks:
    - name: Crear VM desde template con personalización
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
        datacenter: "{{ datacenter_name }}"
        name: "{{ vm_name }}"
        state: poweredon
        template: "{{ template_name }}"
        folder: "{{ folder }}"
        cluster: "{{ cluster_name }}"
        datastore: "{{ datastore_name }}"
        wait_for_ip_address: true
        
        # ⬇️ AGREGAR ESTA LÍNEA PARA USAR LA ESPECIFICACIÓN
        customization_spec: "MOVPER"
        
        # Configuración de red
        networks:
          - name: "Movistar Peru 122"
            device_type: "vmxnet3"
            start_connected: true
            type: "dhcp"
          
      delegate_to: localhost
      register: deploy_vm

    - name: Esperar a que la VM esté completamente lista
      pause:
        minutes: 2
      when: deploy_vm.changed

    - name: Mostrar información de la VM creada
      debug:
        var: deploy_vm.instance.ipv4
