---
- name: Crear VM desde template en vCenter
  hosts: all
  gather_facts: false
  collections:
    - community.vmware
  
  vars:
    vcenter_hostname: "{{ vcenter_host }}"
    vcenter_username: "{{ vcenter_user }}"
    vcenter_password: "{{ vcenter_pass }}"
    datacenter_name: "{{ datacenter }}"
    template_name: "{{ template }}"
    vm_name: "{{ nueva_vm }}"
    # Variables opcionales con valores por defecto
    cluster_name: "{{ cluster | default(omit) }}"
    datastore_name: "{{ datastore | default(omit) }}"
    vm_folder: "{{ folder | default(omit) }}"
    
  tasks:
    - name: Crear VM desde template
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
        datacenter: "{{ datacenter_name }}"
        name: "{{ vm_name }}"
        state: poweredon
        template: "{{ template_name }}"
        # Solo incluye estas si se definen
        cluster: "{{ cluster_name }}"
        folder: "{{ vm_folder }}"
        datastore: "{{ datastore_name }}"
        wait_for_ip_address: true
      delegate_to: localhost
      register: deploy_vm

    - name: Mostrar información de la VM creada
      debug:
        var: deploy_vm
