---
- name: Crear múltiples VMs desde un template en vCenter
  hosts: all
  gather_facts: false
  collections:
    - community.vmware

  vars:
    vcenter_hostname: "{{ vcenter_host }}"
    vcenter_username: "{{ lookup('env', 'VMWARE_USER') }}"
    vcenter_password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
    datacenter_name: "{{ datacenter }}"
    template_name: "{{ template }}"
    vm_name_prefix: "{{ nueva_vm }}"   # Ejemplo: HCIMOVPER201
    cluster_name: "{{ cluster | default(omit) }}"
    datastore_name: "{{ datastore | default(omit) }}"
    vm_folder: "{{ folder | default(omit) }}"

  tasks:
    - name: Calcular número base y prefijo del nombre
      set_fact:
        vm_base_number: "{{ (vm_name_prefix | regex_search('[0-9]+$')) | int }}"
        vm_base_prefix: "{{ vm_name_prefix | regex_replace('[0-9]+$', '') }}"

    - name: Crear lista de nombres de VM
      set_fact:
        vm_names: "{{ vm_names | default([]) + [ vm_base_prefix + ((vm_base_number + item) | string) ] }}"
      loop: "{{ range(0, num_clones) | list }}"

    - name: Mostrar lista de VMs a crear
      debug:
        var: vm_names

    - name: Crear VMs consecutivas
      loop: "{{ vm_names }}"
      loop_control:
        loop_var: vmname
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
        datacenter: "{{ datacenter_name }}"
        name: "{{ vmname }}"
        state: poweredon
        template: "{{ template_name }}"
        cluster: "{{ cluster_name }}"
        folder: "{{ vm_folder }}"
        datastore: "{{ datastore_name }}"
        wait_for_ip_address: true
      delegate_to: localhost
      register: deploy_vms

    - name: Mostrar información de las VMs creadas
      debug:
        var: deploy_vms.results
